kafka_version: "0.9.0.0"
kafka_scala_version: "2.11"
kafka_mesos_git: github.com/mesos/kafka.git
kafka_tar_url: http://www.eu.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{kafka_scala_version}}-{{ kafka_version }}.tgz
kafka_mesos_install_dir: /opt/kafka

mesos_version: "0.27.0"
mesos_lib_file: /usr/lib/libmesos-{{ mesos_version }}.so
mesos_native_java_library: "/usr/local/lib/libmesos.so"
mesos_scheduler_ip: "{{ inventory_hostname }}"
kafka_mesos_scheduler_port: "7000"

kafka_zookeeper_storage: zk:/kafka
is_marathon_app: true
mesos_master: "{{ groups.master[0] }}:5050"
marathon_port: "8080"

#TODO: Add a task to add the app to consul

#consul_host: {{ groups.master[0] }}
#consul_port: "8500"
